// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templatesFiles

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/TymekGluch/Morphyxis-mail-service/internal/templates"
)

func AccountVerified(input templates.AccountVerifiedInput) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"background: #f8fbff; width: 100%; padding: 36px; margin: 0;\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"background: #ffffff; width: 100%; max-width: 600px; margin: 40px auto; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.04); font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;\"><tr><td style=\"padding: 36px; text-align: left;\"><h2 style=\"margin: 0 0 12px 0; color: #2563eb; font-size: 24px; font-weight: 700; letter-spacing: 0.5px;\">Account Successfully Verified</h2><p style=\"margin: 0 0 18px 0; color: #333333; font-size: 16px;\">Hello, <strong>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(input.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/files/account-verified.templ`, Line: 13, Col: 100}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</strong>,</p><p style=\"margin: 0 0 18px 0; color: #333333; font-size: 15px;\">We are pleased to inform you that your account has been successfully verified. You now have full access to all features and services.</p><p style=\"margin: 0 0 0 0; color: #757575; font-size: 13px;\">If you have any questions or need assistance, feel free to contact our support team.</p></td></tr></table></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
