name: Update Package

on:
  pull_request:
  workflow_dispatch:

jobs:
  update-package-on-pull-request:
    name: Update beta version of remote image
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    env:
      IS_BETA_VERSION: "true"
      MORPHYXIS_MAIL_SERVICE_PACKAGE_TOKEN: ${{ secrets.MORPHYXIS_MAIL_SERVICE_PACKAGE_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache-dependency-path: "go.sum"
      - name: Update packages beta version
        run: go build -o update-package cmd/update-package/main.go
      - name: Run update-package
        run: git fetch --tags
        run: ./update-package

  update-package-on-push:
    name: Update stable version of remote image
    runs-on: ubuntu-24.04
    if: github.event_name == 'workflow_dispatch'
    env:
      IS_BETA_VERSION: "false"
      MORPHYXIS_MAIL_SERVICE_PACKAGE_TOKEN: ${{ secrets.MORPHYXIS_MAIL_SERVICE_PACKAGE_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache-dependency-path: "go.sum"
      - name: Update packages stable version
        run: go build -o update-package cmd/update-package/main.go
      - name: Run update-package
        run: git fetch --tags
        run: ./update-package
